### ISSUE TITLE
移动端部分浏览器滑动触发回退

### ISSUE THREAD

**Issue by wbkearly** [author-fuyf/slider-verify-v2#1]
以下是QQ浏览器效果，UC浏览器同理，部分手机如小米默认浏览器也会触发
![sliderverify](https://github.com/author-fuyf/slider-verify-v2/assets/39303119/223c516b-b54f-4c0c-bc29-53afbfc45333)

可以在#circle @touchstart中添加e.preventDefault()
![image](https://github.com/author-fuyf/slider-verify-v2/assets/39303119/00de842a-5eb4-4f4b-82c5-eddd71d5ef02)

**Comment by author-fuyf** [comment]
@wbkearly 感谢指出 最新v1.1.12版本中已修复
